---
title: '`r paste0("GAINS Summaries for ", country)`'
author:
    name: Toph Allen
    affiliation: EcoHealth Alliance
output:
    pdf_document:
        highlight: default
        latex_engine: pdflatex
        template: /Users/toph/.pandoc/templates/latex.template
        keep_tex: false
    word_document:
        highlight: default
    html_document:
        highlight: default
        <!-- template: /Users/toph/.pandoc/templates/html.template -->
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = "~/Dropbox (EHA)/repositories/gains-summary")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Load required packages
library(dplyr)
```

# Animal-level summary data

```{r, include = FALSE}
total_tested <- length(unique(country_gains$AnimalID))
total_positive <- length(unique(country_gains$AnimalID[country_gains$Positive > 0]))
total_risk1 <- length(na.omit(unique(country_gains$AnimalID[country_gains$RiskLevel == "High"])))
```

- Total number of animals tested: `r total_tested`
- Total number of animals tested virus positive `r total_positive`
- Total number of virus-positive animals at RiskLevel = 1: `r total_risk1`

# Frequencies for "high risk" viruses

```{r, results = "asis"}
risk1_viruses <- country_gains %>%
  filter(RiskLevel == "High") %>%
  group_by(VirusName) %>%
  summarize(animals = length(unique(na.omit(AnimalID)))) %>%
  select(VirusName, animals) %>%
  arrange(desc(animals))

knitr::kable(risk1_viruses, col.names = c("Virus name", "Number of animals"), caption = 'Frequencies for "high risk" viruses')
```

# Animals with "high risk" viruses

```{r, results = "asis"}
risk1_individual <- country_gains %>%
  group_by(AnimalID) %>%
  summarize(scientific = unique(SpeciesScientificName),
            common = unique(SpeciesCommonNameEnglish),
            risk1 = ifelse(summary(RiskLevel)["High"] > 0, 1, 0),
            PIG = unique(PrimaryInterfaceGroup),
            SIG = unique(SecondaryInterfaceGroup))

risk1_species <- risk1_individual %>%
  group_by(scientific) %>%
  summarize(common = unique(common),
            animals = length(unique(AnimalID)),
            risk1 = length(risk1[risk1 == 1]),
            percent = round(risk1 / animals * 100, 2)) %>%
  filter(risk1 > 0) %>%
  arrange(desc(percent))

risk1_species$common <- sapply(risk1_species$common, function(x) strsplit(x, " within")[[1]][1])

knitr::kable(risk1_species, col.names = c("Scientific name", "Common name", "Tested", "'High risk'", "%"), caption = "Animals with 'high risk' viruses")
```

# Animals with "medium risk" viruses

```{r, results = "asis"}
risk1_individual <- country_gains %>%
  group_by(AnimalID) %>%
  summarize(scientific = unique(SpeciesScientificName),
            common = unique(SpeciesCommonNameEnglish),
            risk2 = ifelse(summary(RiskLevel)["Medium"] > 0, 1, 0),
            PIG = unique(PrimaryInterfaceGroup),
            SIG = unique(SecondaryInterfaceGroup))

risk1_species <- risk1_individual %>%
  group_by(scientific) %>%
  summarize(common = unique(common),
            animals = length(unique(AnimalID)),
            risk2 = length(risk2[risk2 == 1]),
            percent = round(risk2 / animals * 100, 2)) %>%
  filter(risk2 > 0) %>%
  arrange(desc(percent))

risk1_species$common <- sapply(risk1_species$common, function(x) strsplit(x, " within")[[1]][1])

knitr::kable(risk1_species, col.names = c("Scientific name", "Common name", "Tested", "'Medium risk'", "%"), caption = 'Animals with "medium risk" viruses')
```

# Number of individuals tested per species

```{r, results = "asis"}
animals <- country_gains %>%
  group_by(SpeciesScientificName) %>%
  summarize(SpeciesCommonNameEnglish = unique(SpeciesCommonNameEnglish),
            number = length(unique(AnimalID))) %>%
  arrange(desc(number))

names(animals) <- c("scientific", "common", "number")
animals$common <- sapply(animals$common, function(x) strsplit(x, " within")[[1]][1])

knitr::kable(animals, col.names = c("Scientific name", "Common name", "Number tested"), caption = "Number of individuals tested per species")
```